//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class controlEntities : DbContext
    {
        public controlEntities()
            : base("name=controlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulos> articulos { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<deuda> deuda { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<deudas> deudas { get; set; }
    }
}
